services:
  downtify:
    container_name: downtify
    image: 'downtify:${TAG-latest}'
    restart: unless-stopped
    build: .
    ports:
      - '8000:30321'
    volumes:
      - ./downloads/docker:/downloads
      - ./frontend/dist:/downtify/frontend/dist:ro
    environment:
      - DOWNTIFY_PORT=30321
    dns:
      - 1.1.1.1
      - 1.0.0.1
